# 有关如何配置 Wrangler 的更多详细信息，请参阅：
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "mfjip612-github-io"
compatibility_date = "2025-12-05"
main = "server/index.js"

[assets]
not_found_handling = "single-page-application"

[observability]
enabled = true

# 智能放置
# 文档：https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# placement = { mode = "smart" }

# 绑定
# 绑定允许您的 Worker 与 Cloudflare 开发者平台上的资源交互，包括
# 数据库、对象存储、AI推理、实时通信等。
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

# 环境变量
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# 注意：使用 secrets 存储敏感数据。
# https://developers.cloudflare.com/workers/configuration/secrets/

# 静态资源
# https://developers.cloudflare.com/workers/static-assets/binding/
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# 服务绑定（在多个 Worker 之间通信）
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"